version: "3.8"

services:
  app:
    build: .
    # Or use prebuild image with:
    # image: sythinian/lab-index-tracker:latest
    ports:
      - "8000:8000"
    volumes:
      - services_data:/data

volumes:
  services_data:
